### ISSUE TITLE
Cursor can be left in the opening cover when page 1 is visible

### ISSUE THREAD

**Issue by Cervator** [Terasology/Books#3]
Can't actually write anything so it is a pretty minor cosmetic issue.

To replicate: open a book, without changing pages (should start with the inside of the front cover + page one visible) click in the upper left of the inside cover and a blinking cursor will appear. You can't do anything with it like write stuff.

**Comment by iojw** [comment]
This has to do with how `UIText` widgets draw the cursor even if the widget is read-only. To fix this, we might need to modify `UIText` such that we are able to specify that the cursor should not be drawn.

**Comment by Cervator** [comment]
Ok! So this might be more of an engine issue then? We could move this issue there if so.

**Comment by iojw** [comment]
Yup, but I'm not sure if this really warrants an issue. It seems like a really minor customisation tweak that would take around 2 lines of code 😄. I could just add it along with my next PR to the main repo. Or maybe the issue might could just be for increasing the customisation options for widgets in general.

**Comment by Cervator** [comment]
Closing as resolved some time ago by #14
