### ISSUE TITLE
Re-implement some unique functionality for bookcases

### ISSUE THREAD

**Issue by Cervator** [Terasology/Books#5]
Way back in the olden days, in the time before time, bookcases had a filter on what items they would accept (only books, naturally). This was removed over time as the engine matured, and we might not have the original event anymore.

Mentioned briefly with more details at the bottom of #2

**Comment by iojw** [comment]
The event in question in the new engine is `BeforeItemPutInInventory`. 

I'll have to figure how to make the bookcase drop its items on destroy before I take this one on.

**Comment by iojw** [comment]
Relevant classes for making the bookcasse drop items are `CreateBlockDropsEvent` and `DropItemEvent`, in case anyone would like to work on this before I get a chance to 🙂.
